// <auto-generated />
using System;
using ManagementHub.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementHub.Storage.Migrations
{
    [DbContext(typeof(ManagementHubDbContext))]
    [Migration("20260724_AddFlagRunnerRefereesCountColumn")]
    partial class AddFlagRunnerRefereesCountColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ManagementHub.Models.Data.NationalGoverningBodyStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AssistantRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("assistant_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("CommunityTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("community_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("CompetitiveTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("competitive_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DevelopingTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("developing_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("FlagRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("flag_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("FlagRunnerRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("flag_runner_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("HeadRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("head_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("InactiveTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("inactive_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("NationalGoverningBodyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("national_governing_body_id");

                    b.Property<int?>("ScorekeeperRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("scorekeeper_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("SnitchRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("snitch_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<int?>("TeamStatusChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("team_status_change_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("TotalRefereesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_referees_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("TotalTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("UncertifiedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("uncertified_count")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("UniversityTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("university_teams_count")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YouthTeamsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("youth_teams_count")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationalGoverningBodyId" }, "ngb_stats_on_ngb_id");

                    b.ToTable("national_governing_body_stats", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
