// <auto-generated />
using System;
using ManagementHub.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementHub.Storage.Migrations
{
    [DbContext(typeof(ManagementHubDbContext))]
    [Migration("20260724_UpdateFlagRunnerCertifications")]
    partial class UpdateFlagRunnerCertifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ManagementHub.Models.Data.ActiveStorageAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BlobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blob_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<long>("RecordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("record_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BlobId" }, "index_active_storage_attachments_on_blob_id");

                    b.HasIndex(new[] { "RecordType", "RecordId", "Name", "BlobId" }, "index_active_storage_attachments_uniqueness")
                        .IsUnique();

                    b.ToTable("active_storage_attachments", (string)null);
                });

            modelBuilder.Entity("ManagementHub.Models.Data.ActiveStorageBlob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_size");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .HasColumnType("character varying")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("filename");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("key");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "index_active_storage_blobs_on_key")
                        .IsUnique();

                    b.ToTable("active_storage_blobs", (string)null);
                });

            modelBuilder.Entity("ManagementHub.Models.Data.Certification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("ManagementHub.Models.Data.NgbSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CertificationLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("certification_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("NgbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ngb_id");

                    b.Property<int>("RefereeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("referee_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NgbId", "CertificationLevel" }, "index_ngb_snapshots_on_ngb_id_and_certification_level")
                        .IsUnique();

                    b.ToTable("ngb_snapshots", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
