version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  test_ruby:
    working_directory: ~/referee_hub
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: referee_hub
          RAILS_ENV: test
          DATABASE_URL_TEST: postgres://referee_hub:@localhost:5432/referee_hub_test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: referee_hub
          POSTGRES_DB: referee_hub_test
          POSTGRES_PASSWORD: ""
      - image: circleci/redis:4.0.9-alpine

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install ruby dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run ruby tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec $TEST_FILES
      - codecov/upload:
          file: coverage/.resultset.json

  test_js:
    working_directory: ~/referee_hub
    docker:
      - image: circleci/node:14.15.0

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn and dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: |
            mkdir -p ./tmp/js-test-results
            yarn test:ci
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test_ruby
      - test_js
