const path = require('path');
const Dotenv = require('dotenv-webpack');
const { merge } = require('webpack-merge');
const common = require('./webpack.config.common.js');

module.exports = merge(common, {
  // Enable filesystem cache for faster rebuilds
  cache: {
    type: 'filesystem',
    buildDependencies: {
      config: [__filename],
    },
  },
  devtool: 'eval-cheap-module-source-map',
  mode: 'development',
  output: {
    // Keep CSS and copied images generated by separate scripts.
    clean: false,
    filename: '[name].js',
    chunkFilename: '[name].js',
  },
  plugins: [
    new Dotenv(),
  ],
  devServer: {
    // Keep a fixed dev port to avoid split runtimes across 8080/8081.
    port: 8080,
    // Force index.html for all non-asset routes such as /sign_in.
    historyApiFallback: {
      disableDotRule: true,
      index: '/index.html',
      rewrites: [
        { from: /./, to: '/index.html' },
      ],
    },
    // Keep webpack bundles in memory to avoid duplicate static middleware responses.
    devMiddleware: {
      writeToDisk: false,
    },
    // Enable Hot Module Replacement
    hot: true,
    // Disable live reload (HMR will handle updates)
    liveReload: false,
    // Watch files for changes
    watchFiles: {
      paths: ['app/**/*', 'assets/**/*'],
      options: {
        usePolling: false, // Use native file system events for better performance
      },
    },
    // Client configuration for better error reporting
    client: {
      overlay: {
        errors: true,
        warnings: false,
      },
      // WebSocket URL configuration - explicitly point to webpack dev server port
      webSocketURL: {
        hostname: 'localhost',
        pathname: '/ws',
        port: 8080,
        protocol: 'ws',
      },
    },
    // Allow access from any host (useful for development)
    allowedHosts: 'all',
    // Enable compression
    compress: true,
    // Headers for CORS during development
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    // Forward backend routes to ASP.NET service running on localhost:5000.
    proxy: [
      {
        context: ['/api', '/hubs', '/sign_in'],
        target: 'http://localhost:5000',
        changeOrigin: true,
        secure: false,
      },
    ],
    // Static files configuration
    static: {
      directory: path.join(__dirname, 'dist'),
      watch: true,
    },
  },
});