using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using FluentAssertions;
using ManagementHub.IntegrationTests.Helpers;
using ManagementHub.IntegrationTests.Models;
using ManagementHub.Service.Filtering;
using Xunit;

namespace ManagementHub.IntegrationTests;

/// <summary>
/// Integration tests for NGB Team CRUD operations.
/// Tests creating, updating, retrieving, and deleting teams with various data including special characters.
/// Uses Testcontainers to run against a real PostgreSQL database.
/// </summary>
public class NgbTeamCrudApiIntegrationTests : IClassFixture<TestWebApplicationFactory>
{
	private readonly TestWebApplicationFactory _factory;
	private readonly HttpClient _client;

	public NgbTeamCrudApiIntegrationTests(TestWebApplicationFactory factory)
	{
		this._factory = factory;
		this._client = this._factory.CreateClient();
	}

	[Fact]
	public async Task CreateTeam_WithSpecialCharacters_ShouldPreserveCharacters()
	{
		// Arrange: Sign in as NGB admin
		await AuthenticationHelper.AuthenticateAsAsync(this._client, "ngb_admin@example.com", "password");

		// Create request without TeamId (which is generated by backend)
		var teamRequest = new
		{
			Name = "Selección Española de Quadball",
			City = "Madrid",
			Country = "Spain",
			Status = "Competitive",
			GroupAffiliation = "University",
			JoinedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString("yyyy-MM-dd"),
			SocialAccounts = Array.Empty<object>()
		};

		// Act: Create team with special characters
		var createResponse = await this._client.PostAsJsonAsync("/api/v2/Ngbs/USA/teams", teamRequest);

		// Debug: Log error if not successful
		if (!createResponse.IsSuccessStatusCode)
		{
			var errorContent = await createResponse.Content.ReadAsStringAsync();
			throw new Exception($"Team creation failed with status {createResponse.StatusCode}: {errorContent}");
		}

		// Assert: Team creation should succeed
		createResponse.StatusCode.Should().Be(HttpStatusCode.OK,
			"NGB admin should be able to create teams in their NGB");

		var createdTeam = await createResponse.Content.ReadFromJsonAsync<NgbTeamViewModelDto>();
		createdTeam.Should().NotBeNull();
		createdTeam!.TeamId.Should().NotBeNullOrEmpty("created team should have an ID");

		// Verify special characters are preserved exactly
		createdTeam.Name.Should().Be("Selección Española de Quadball",
			"special characters (ó, ñ) should be preserved in the team name");

		// Act: Retrieve the team to verify persistence
		var getResponse = await this._client.GetAsync($"/api/v2/Ngbs/USA/teams/{createdTeam.TeamId}");

		// Note: If there's no direct GET endpoint for a single team, we'll verify through the list
		// For now, let's verify through the list endpoint
		var listResponse = await this._client.GetAsync("/api/v2/Ngbs/USA/teams");
		listResponse.StatusCode.Should().Be(HttpStatusCode.OK);

		var teamsResponse = await listResponse.Content.ReadFromJsonAsync<Filtered<NgbTeamViewModelDto>>();
		teamsResponse.Should().NotBeNull();
		var teams = teamsResponse!.Items.ToList();

		// Find the team we just created
		var retrievedTeam = teams.FirstOrDefault(t => t.TeamId == createdTeam.TeamId);
		retrievedTeam.Should().NotBeNull("created team should appear in the list");
		retrievedTeam!.Name.Should().Be("Selección Española de Quadball",
			"special characters should be preserved when retrieving from database");
	}

	[Fact]
	public async Task CreateTeam_WithVariousSpecialCharacters_ShouldPreserveAll()
	{
		// Arrange: Sign in as NGB admin
		await AuthenticationHelper.AuthenticateAsAsync(this._client, "ngb_admin@example.com", "password");

		// Test various special characters from different languages
		var testCases = new[]
		{
			"Équipe Française de Quidditch", // French accents
			"São Paulo Quidditch Club", // Portuguese
			"Düsseldorf Hexen", // German umlauts
			"Москва Квиддич", // Cyrillic
			"日本クィディッチ", // Japanese
			"القاهرة كويدتش", // Arabic
			"Kraków Dragons", // Polish
			"Αθήνα Κουίντιτς", // Greek
		};

		foreach (var teamName in testCases)
		{
			var teamRequest = new
			{
				Name = teamName,
				City = "Test City",
				Country = "Test Country",
				Status = "Competitive",
				GroupAffiliation = "Community",
				JoinedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString("yyyy-MM-dd"),
				SocialAccounts = Array.Empty<object>()
			};

			// Act: Create team
			var createResponse = await this._client.PostAsJsonAsync("/api/v2/Ngbs/USA/teams", teamRequest);

			// Assert: Team creation should succeed
			createResponse.StatusCode.Should().Be(HttpStatusCode.OK,
				$"team creation should succeed for: {teamName}");

			var createdTeam = await createResponse.Content.ReadFromJsonAsync<NgbTeamViewModelDto>();
			createdTeam.Should().NotBeNull();
			createdTeam!.Name.Should().Be(teamName,
				$"special characters should be preserved for: {teamName}");
		}
	}

	[Fact]
	public async Task UpdateTeam_WithSpecialCharacters_ShouldPreserveCharacters()
	{
		// Arrange: Sign in as NGB admin and create a team first
		await AuthenticationHelper.AuthenticateAsAsync(this._client, "ngb_admin@example.com", "password");

		var initialTeamRequest = new
		{
			Name = "Test Team",
			City = "Barcelona",
			Country = "Spain",
			Status = "Competitive",
			GroupAffiliation = "University",
			JoinedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString("yyyy-MM-dd"),
			SocialAccounts = Array.Empty<object>()
		};

		var createResponse = await this._client.PostAsJsonAsync("/api/v2/Ngbs/USA/teams", initialTeamRequest);
		createResponse.StatusCode.Should().Be(HttpStatusCode.OK);
		var createdTeam = await createResponse.Content.ReadFromJsonAsync<NgbTeamViewModelDto>();
		createdTeam.Should().NotBeNull();

		// Act: Update team name to include special characters
		createdTeam!.Name = "Cataluña Quadball Federació";
		var updateResponse = await this._client.PutAsJsonAsync($"/api/v2/Ngbs/USA/teams/{createdTeam.TeamId}", createdTeam);

		// Assert: Update should succeed
		updateResponse.StatusCode.Should().Be(HttpStatusCode.OK,
			"NGB admin should be able to update teams in their NGB");

		var updatedTeam = await updateResponse.Content.ReadFromJsonAsync<NgbTeamViewModelDto>();
		updatedTeam.Should().NotBeNull();
		updatedTeam!.Name.Should().Be("Cataluña Quadball Federació",
			"special characters (ñ, ó) should be preserved when updating team name");

		// Verify persistence by retrieving the list
		var listResponse = await this._client.GetAsync("/api/v2/Ngbs/USA/teams");
		listResponse.StatusCode.Should().Be(HttpStatusCode.OK);

		var teamsResponse = await listResponse.Content.ReadFromJsonAsync<Filtered<NgbTeamViewModelDto>>();
		var teams = teamsResponse!.Items.ToList();
		var retrievedTeam = teams.FirstOrDefault(t => t.TeamId == updatedTeam.TeamId);

		retrievedTeam.Should().NotBeNull();
		retrievedTeam!.Name.Should().Be("Cataluña Quadball Federació",
			"special characters should persist after update");
	}

	[Fact]
	public async Task GetNgbTeams_WithSpecialCharactersInDatabase_ShouldReturnCorrectly()
	{
		// Arrange: Sign in as NGB admin and create multiple teams with special characters
		await AuthenticationHelper.AuthenticateAsAsync(this._client, "ngb_admin@example.com", "password");

		var spanishTeamRequest = new
		{
			Name = "Selección Española",
			City = "Madrid",
			Country = "Spain",
			Status = "Competitive",
			GroupAffiliation = "Community",
			JoinedAt = DateOnly.FromDateTime(DateTime.UtcNow).ToString("yyyy-MM-dd"),
			SocialAccounts = Array.Empty<object>()
		};

		await this._client.PostAsJsonAsync("/api/v2/Ngbs/USA/teams", spanishTeamRequest);

		// Act: Retrieve all teams
		var response = await this._client.GetAsync("/api/v2/Ngbs/USA/teams");

		// Assert: Response should be successful
		response.StatusCode.Should().Be(HttpStatusCode.OK,
			"retrieving teams should succeed even with special characters in database");

		var teamsResponse = await response.Content.ReadFromJsonAsync<Filtered<NgbTeamViewModelDto>>();
		teamsResponse.Should().NotBeNull();
		var teams = teamsResponse!.Items.ToList();

		teams.Should().NotBeNull();
		teams.Should().Contain(t => t.Name == "Selección Española",
			"team with special characters should appear in the list with correct name");
	}
}
